

-- 모든 테이블 확인
SELECT * FROM TABS

-- 테이블 생성
CREATE TABLE KOPO_PRODUCT_VOLUME
(
    REGIOND VARCHAR(20 BYTE),
    PRODUCTGROUP VARCHAR(20 BYTE),
    YEARWEEK VARCHAR(6 BYTE),
    VOLUME NUMBER
)

-- 테이블 조회
SELECT * FROM KOPO_PRODUCT_VOLUME

-- 테이블의 설명 보기 : 테이블명 더블클릭 후 F4를 누르면 됨
DESC KOPO_PRODUCT_VOLUME