

-- 모든 테이블 확인
SELECT * FROM TABS;

-- 테이블 생성 및 기본키 지정
CREATE TABLE KOPO_PRODUCT_VOLUME_김동준
(
    REGIONID VARCHAR(20 BYTE),
    PRODUCTGROUP VARCHAR(20 BYTE),
    YEARWEEK VARCHAR(6 BYTE),
    VOLUME NUMBER NOT NULL,
    CONSTRAINTS PK_KOPO_PRODUCT_VOLUME_김동준 PRIMARY KEY(REGIONID,PRODUCTGROUP,YEARWEEK)
);

-- 테이블 조회
SELECT * FROM KOPO_PRODUCT_VOLUME_김동준;

-- 테이블의 설명 보기 : 테이블명 더블클릭 후 F4를 누르면 됨
DESC KOPO_PRODUCT_VOLUME_김동준;

-- 테이블 삭제
DROP TABLE KOPO_PRODUCT_VOLUME_김동준;

-- 데이터 넣기1 : 각 컬럼의 속성에 어긋난 데이터를 넣으면 도메인 무결정 제약 조건에 위배
INSERT INTO KOPO_PRODUCT_VOLUME_김동준
VALUES('REGIONID', 'PRODUCTGROUP', '201702', 2); -- VOLUME(NUMBER)에 문자를 넣어서 오류

-- 데이터 넣기2 : 기본 키로 지정한 컬럼에 중복된 데이터를 넣으면 개체 무결성 제약 조건에 위배
INSERT INTO KOPO_PRODUCT_VOLUME_김동준
VALUES('REGIONID', 'PRODUCTGROUP', '201702', 1);

INSERT INTO KOPO_PRODUCT_VOLUME_김동준
VALUES('REGIONID', 'PRODUCTGROU', '201702', 2); -- 기본 키로 지정한 것들이 중복된 내용이므로 오류

-- 또한 NUMBER 속성에 NOT NULL로 설정해서 VOLUME에 NULL값을 넣으려면 오류