-- 다른 데이터베이스 서버에 연결해서 자료를 가져오는 것

-- LINK_NAME : 링크 이름
CREATE DATABASE LINK LINK_NAME
CONNECT TO KOPO2019
IDENTIFIED BY kopo2019
USING '[DEV]KOPO';

SELECT * FROM TABS@LINK_NAME;

-- LINK_NAME 이라는 링크 삭제
DROP DATABASE LINK LINK_NAME;

CREATE TABLE KOPO_PRODUCT_VOLUME_LINK
AS SELECT * FROM KOPO_PRODUCT_VOLUME@LINK_NAME;

SELECT * FROM KOPO_PRODUCT_VOLUME_LINK;

INSERT INTO KOPO_PRODUCT_VOLUME_LINK
SELECT * FROM KOPO_PRODUCT_VOLUME@LINK_NAME;