CREATE TABLE KOPO_REGION_MASTER(
    REGIONID VARCHAR2(100),
    REGIONNAME VARCHAR2 (100));
    
SELECT * FROM KOPO_PRODUCT_VOLUME;

TRUNCATE TABLE KOPO_PRODUCT_VOLUME;

EDIT KOPO_PRODUCT_VOLUME;

SELECT * FROM KOPO_REGION_MASTER;

EDIT KOPO_REGION_MASTER;

SELECT * FROM
KOPO_REGION_MASTER A
LEFT JOIN KOPO_PRODUCT_VOLUME B
ON A.REGIONID = B.REGIOND