CREATE TABLE KOPO_REGION_MASTER(
    REGIONID VARCHAR2(100),
    REGIONNAME VARCHAR2 (100));
    
SELECT * FROM KOPO_PRODUCT_VOLUME;

TRUNCATE TABLE KOPO_PRODUCT_VOLUME;

EDIT KOPO_PRODUCT_VOLUME;

SELECT * FROM KOPO_REGION_MASTER;

EDIT KOPO_REGION_MASTER;

SELECT * FROM
KOPO_REGION_MASTER A
LEFT JOIN KOPO_PRODUCT_VOLUME B
ON A.REGIONID = B.REGIOND;

-- INNER JOIN시 작은 데이터를 앞에 넣음 -> 성능향상
SELECT B.REGIONID, A.REGIONNAME, B.PRODUCT, B.YEARWEEK, B.QTY
FROM KOPO_REGION_MST A
INNER JOIN KOPO_CHANNEL_SEASONALITY_NEW B
ON A.REGIONID = B.REGIONID;

SELECT A.REGIONID, B.REGIONNAME, A.PRODUCT, A.YEARWEEK, A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A
LEFT JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID;

SELECT A.REGIONID, B.REGIONNAME, A.PRODUCT, A.YEARWEEK, A.QTY
FROM KOPO_CHANNEL_SEASONALITY_NEW A
RIGHT JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID;

SELECT B.REGIONID, A.REGIONNAME, B.PRODUCT, B.YEARWEEK, B.QTY
FROM KOPO_REGION_MST A
FULL OUTER JOIN KOPO_CHANNEL_SEASONALITY_NEW B
ON A.REGIONID = B.REGIONID;