SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW;

SELECT * FROM KOPO_REGION_MST;

-- INNER JOIN
SELECT
    A.*,
    B.REGIONNAME
FROM KOPO_CHANNEL_SEASONALITY_NEW A
INNER JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID;

SELECT A.*, B.REGIONNAME
FROM KOPO_CHANNEL_SEASONALITY_NEW A,
KOPO_REGION_MST B
WHERE A.REGIONID = B.REGIONID;

-- LEFT JOIN
SELECT
    A.*,
    B.REGIONNAME
FROM KOPO_CHANNEL_SEASONALITY_NEW A
LEFT JOIN KOPO_REGION_MST B
ON A.REGIONID = B.REGIONID;

SELECT A.*, B.REGIONNAME
FROM KOPO_CHANNEL_SEASONALITY_NEW A,
KOPO_REGION_MST B
WHERE A.REGIONID = B.REGIONID(+);

-- CROSS JOIN (Ä«Æ¼¼Ç °ö)
SELECT A.*, B.* FROM CUSTOMERDATA A, CUSTOMER_NAME B;

SELECT A.*, B.*
FROM CUSTOMERDATA A
CROSS JOIN CUSTOMER_NAME B;