CREATE TABLE KOPO_CATEGORY
(
    CATCODE VARCHAR2(100 BYTE),
    NAME VARCHAR2(100 BYTE),
    CONSTRAINTS PK_KOPO_CATEGORY PRIMARY KEY(CATCODE)
);

CREATE TABLE KOPO_PRODUCT
(
    PRODUCTCODE VARCHAR2(100 BYTE),
    CATCODE_FK VARCHAR2(100 BYTE),
    NAME VARCHAR2(100 BYTE),
    COMPANY VARCHAR2(100 BYTE),
    PRICE NUMBER NOT NULL,
    BUY_NUM NUMBER NOT NULL,
    STATUS VARCHAR2(100 BYTE),
    DETAILS VARCHAR2(100 BYTE),
    C_DATE VARCHAR2(100 BYTE),
    CONSTRAINTS PK_KOPO_PRODUCT PRIMARY KEY(PRODUCTCODE),
    CONSTRAINT FK_KOPO_PRODUCT FOREIGN KEY (CATCODE_FK) REFERENCES KOPO_CATEGORY (CATCODE)
);

CREATE TABLE KOPO_USERS
(
    USERID VARCHAR2(100 BYTE),
    USERNAME VARCHAR2(100 BYTE),
    PASSWORD VARCHAR2(100 BYTE),
    CARD_COMPANY VARCHAR2(100 BYTE),
    CARD_NO VARCHAR2(100 BYTE),
    ADDRESS VARCHAR2(100 BYTE),
    TEL VARCHAR2(100 BYTE),
    EMAIL VARCHAR2(100 BYTE),
    CONSTRAINTS PK_KOPO_USERS PRIMARY KEY(USERID)
);

CREATE TABLE KOPO_ORDER
(
    ORDERID VARCHAR2(100 BYTE),
    USERID_FK VARCHAR2(100 BYTE),
    ORDER_STATUS VARCHAR2(100 BYTE) CHECK (ORDER_STATUS = '0' OR ORDER_STATUS = '1'),
    ORDER_DATE VARCHAR2(100 BYTE),
    ORDER_PRICE NUMBER NOT NULL,
    CONSTRAINTS PK_KOPO_ORDER PRIMARY KEY(ORDERID),
    CONSTRAINT FK_KOPO_ORDER FOREIGN KEY (USERID_FK) REFERENCES KOPO_USERS (USERID)
);

CREATE TABLE KOPO_ORDER_LIST
(
    ORDERID_FK VARCHAR2(100 BYTE),
    PRODUCTCODE_FK VARCHAR2(100 BYTE),
    COUNT NUMBER NOT NULL,
    CONSTRAINTS PF_KOPO_ORDER_LIST PRIMARY KEY(ORDERID_FK, PRODUCTCODE_FK),
    CONSTRAINT FK1_KOPO_ORDER_LIST FOREIGN KEY (ORDERID_FK) REFERENCES KOPO_ORDER (ORDERID),
    CONSTRAINT FK2_KOPO_ORDER_LIST FOREIGN KEY (PRODUCTCODE_FK) REFERENCES KOPO_PRODUCT (PRODUCTCODE)
);

DROP TABLE KOPO_ORDER_LIST;

SELECT * FROM KOPO_ORDER_LIST;

INSERT INTO KOPO_ORDER_LIST
VALUES('ORDER6', 'PRODUCTCODE', 11010124);

DELETE FROM KOPO_PRODUCT
WHERE PRODUCTCODE = 'PRODUCTCODE1';