SELECT * FROM KOPO_CHANNEL_RESULT T1
LEFT JOIN KOPO_REGION_MST T2
ON (T1.AP2ID = T2.REGIONID)
WHERE T2.REGIONNAME IN('AMERICA')
AND (T1.YEARWEEK BETWEEN 201724 AND 201725 
    OR T1.YEARWEEK BETWEEN 201727 AND 201729
    )
AND T1.AP1NAME IN('BEST BUY', 'HOME DEPOT')
AND T1.PRODUCT IN('HHP');

SELECT
   REGIONID, PRODUCTGROUP, YEARWEEK
FROM KOPO_PRODUCT_VOLUME
WHERE PRODUCTGROUP = &PRODUCT
OR YEARWEEK = '201544';

-- 사용자 입력값 받기
SELECT * FROM KOPO_PROMOTION
WHERE TARGETWEEK BETWEEN &STARTWEEK AND &ENDWEEK
ORDER BY ITEM DESC, TARGETWEEK ASC;

-- 정렬
SELECT * FROM KOPO_PRODUCT_VOLUME
ORDER BY REGIONID ASC, PRODUCTGROUP ASC, YEARWEEK ASC;

-- 대/소문자 변경
SELECT 
   UPPER(PRODUCT) AS CASE1,
   LOWER(PRODUCT) AS CASE2
FROM KOPO_CHANNEL_SEASONALITY_NEW;

-- 함수를 실험하도록 제공해주는 테이블
SELECT UPPER('AAAAabc') AS TEST FROM DUAL;

-- 컬럼 값 합치기
SELECT 
    -- COMCAT은 단점이 2개를 초과하여 붙일 경우 중첩으로 써줘야 함
    CONCAT(REGIONID, CONCAT('_', PRODUCT)) AS KEYCOL1,
    REGIONID || '_' || PRODUCT AS KEYCOL2
FROM KOPO_CHANNEL_SEASONALITY_NEW;

-- 컬럼 값 추출하기
SELECT 
    -- SUBSTR(찾을 문자열, 시작점, 끝점)
    PRODUCT,
    SUBSTR(PRODUCT, 1, 7)
FROM KOPO_CHANNEL_SEASONALITY_NEW;

-- 컬럼 값 채우기
SELECT 
    LPAD(PRODUCT, 15, '0') AS L,
    RPAD(PRODUCT, 15, '0') AS R
FROM KOPO_CHANNEL_SEASONALITY_NEW;

SELECT
    LPAD(CUSTOMERCODE, 12, '*') AS NEWCUSTOMERCODE
FROM KOPO_CUSTOMERDATA;

-- 컬럼 값 제거하기
SELECT 
    PRODUCT,
    -- 보통은 TRIM으로 양옆 공백을 제거함
    TRIM(PRODUCT),
    LTRIM(PRODUCT,'PRO'),
    RTRIM(PRODUCT, '56')
FROM KOPO_CHANNEL_SEASONALITY_NEW;

-- 컬럼 값 변경하기
SELECT 
    REGIONID,
    REPLACE(REGIONID,'A','REGION')
FROM KOPO_CHANNEL_SEASONALITY_NEW;

SELECT
    LPAD(
        REPLACE(
            CUSTOMERCODE,
            SUBSTR(CUSTOMERCODE,
                LENGTH(CUSTOMERCODE) - 3,
                LENGTH(CUSTOMERCODE)
            ), 
            '****'
        ),
        10,
        '0'
    ) AS CUSTOMER_PASSWORD
FROM KOPO_CUSTOMERDATA;